Upgrade Axios dependency
localtunnel/localtunnel pull request #432
Opened 2021-09-07 18:24 UTC by JuanVqz

2021-09-08 23:17 UTC, akaraman85 commented
Ran into this issue with a security vulnerability scan.  👍 on the merge.

2021-09-09 14:23 UTC, AJ1039593 approved these changes

2021-09-10 15:40 UTC, raniesantos commented
I also encountered this issue. Waiting for the merge.

2021-09-13 17:04 UTC, raniesantos commented
Is defunctzombie the only one with permissions to merge this?

2021-09-13 17:09 UTC, TheBoroer commented
@raniesantos yes he is.

@defunctzombie this look good to me to get merged in :) 
If he hapepns to not see this, I'll ping him in other channels

2021-09-15 03:00 UTC, defunctzombie requested changes

2021-09-15 03:00 UTC, defunctzombie commented on CHANGELOG.md
> +# 2.0.2 (2021-09-07)
PRs should not bump this. This is up to maintainer to decide what version bump to make.

2021-09-15 03:57 UTC, defunctzombie approved these changes

2021-09-15 03:57 UTC, merged

2021-09-15 04:29 UTC, raniesantos commented
Thanks

2021-09-16 10:07 UTC, giamir commented
@defunctzombie When a new version will be released in npm with this patch? Thanks